import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ActionCard, PageTitle } from '../components/PageParts'
import { Badge, Shell, SidePanel } from '../components/Shell'
import { jobs } from '../data/jobs'

export function JobDetailPage() {
  const {id}=useParams(); const job=jobs.find(item=>item.id===id)??jobs[0]; const [tab,setTab]=useState<'reason'|'work'>('reason'); const [source,setSource]=useState(false)
  return <Shell><main className="content two-column"><section><Link className="back" to="/jobs">← 직무 찾기로</Link><PageTitle eyebrow={job.company} title={job.title}/><div className="metadata"><Badge tone="green">{job.verdict}</Badge><Badge>적합도 {job.fit}</Badge><span>{job.location}</span><span>{job.seats}명 모집</span></div><div className="detail-tabs tabs"><button className={tab==='reason'?'active':''} onClick={()=>setTab('reason')}>판정 이유</button><button className={tab==='work'?'active':''} onClick={()=>setTab('work')}>하는 일 · 기관</button></div>{tab==='reason'?<><section className="card reason-card"><h2>지원 조건을 이렇게 확인했어요</h2>{[['학년','3학년부터 지원할 수 있어요.','3'],['전공','디자인·뷰티 관련 전공을 우대해요.','4'],['이수 학기','4학기 이상 기준을 충족했어요.','3']].map(([title,text,page])=><div className="reason-row" key={title}><b>✓ {title}</b><span>{text}</span><button onClick={()=>setSource(true)}>원문 {page}쪽</button></div>)}</section><section className="card commute"><h2>통근</h2><p><b>서울 성북구</b>에서 출발 · 카카오맵 대중교통 기준</p><div><strong>약 48분</strong><span>지하철 2회 환승 · 도보 8분</span></div><small>통근 결과는 저장하지 않아요.</small></section></>:<section className="card work-card"><h2>이런 일을 해요</h2><ul><li>브랜드 SNS 콘텐츠 주제와 일정을 기획해요.</li><li>촬영·편집 과정에 참여하고 성과를 정리해요.</li><li>고객 반응과 시장 흐름을 조사해요.</li></ul><h2>기관 정보</h2><p>뷰티 브랜드의 디지털 경험을 만드는 42명 규모의 기업입니다.</p></section>}</section><ActionCard action={<Link className="button primary full" to="/plan">담고 내 지망에서 순서 정하기</Link>}><h3>내 지망에 담아두기</h3><p>담은 뒤 1~3지망 순서를 정할 수 있어요.</p></ActionCard>{source&&<SidePanel title="출처 · AI가 읽은 값" close={()=>setSource(false)}><h3>지원 자격</h3><blockquote>“관련 전공 3학년 이상이며 4학기 이상 이수한 재학생”</blockquote><p className="source">2026 하계 현장실습 모집계획 · 3쪽</p><p className="notice">AI가 읽은 값은 원문과 다를 수 있어요. 최종 지원 전 반드시 확인하세요.</p></SidePanel>}</main></Shell>
}
