import { useState } from 'react'
import { Link } from 'react-router-dom'
import { PageTitle } from '../components/PageParts'
import { Badge, Modal, Shell, SidePanel } from '../components/Shell'
import { jobs, type Job } from '../data/jobs'

export function JobsPage() {
  const [evidence,setEvidence]=useState<Job|null>(null); const [saved,setSaved]=useState<string[]>([]); const [guide,setGuide]=useState(false)
  const save=(id:string)=>{if(!saved.includes(id)){setSaved([...saved,id]);if(saved.length===0)setGuide(true)}}
  return <Shell><main className="content wide"><div className="space-between"><PageTitle eyebrow="내 조건으로 찾은 결과" title="지원할 수 있는 직무를 모았어요" description="판정 이유를 공고 원문과 함께 확인해 보세요."/><div className="result-summary"><b>추천 5</b><span>지원 가능 3 · 확인 필요 2</span></div></div><section className="recommendations">{jobs.map(job=><article className="recommend-card" key={job.id}><div><Badge tone={job.verdict==='지원 가능'?'green':'orange'}>{job.verdict}</Badge><Badge>적합도 {job.fit}</Badge></div><small>{job.company}</small><h3><Link to={`/jobs/${job.id}`}>{job.title}</Link></h3><p>{job.location}</p><button className="link-button" onClick={()=>setEvidence(job)}>근거 보기 →</button></article>)}</section><section className="card jobs-list"><div className="list-header"><b>전체 직무</b><div className="filter"><button className="selected">전체</button><button>지원 가능</button><button>확인 필요</button></div></div>{jobs.map(job=><div className="job-row" key={job.id}><div><Link to={`/jobs/${job.id}`}><b>{job.title}</b></Link><small>{job.company} · {job.location}</small></div><div><Badge>콘텐츠 기획</Badge><Badge>실무 경험</Badge></div><Badge tone={job.verdict==='지원 가능'?'green':'orange'}>{job.verdict}</Badge><span>{job.seats}명 모집</span><button className={`save-button ${saved.includes(job.id)?'saved':''}`} onClick={()=>save(job.id)}>{saved.includes(job.id)?'담았어요':'담기'}</button></div>)}</section>{evidence&&<SidePanel title="이렇게 판단했어요" close={()=>setEvidence(null)}><Badge tone={evidence.verdict==='지원 가능'?'green':'orange'}>{evidence.verdict}</Badge><h3>{evidence.title}</h3><p>학년과 이수 학기 조건에 맞고, 전공 우대 항목이 프로필과 연결돼요.</p><blockquote>“관련 전공 재학생으로 4학기 이상 이수한 학생”</blockquote><p className="source">2026학년도 하계 현장실습 모집공고 · 3쪽</p><Link className="button primary full" to={`/jobs/${evidence.id}`}>직무 상세 보기</Link></SidePanel>}{guide&&<Modal close={()=>setGuide(false)}><div className="complete-icon">✓</div><h2>첫 직무를 담았어요</h2><p>담은 직무는 익명으로 집계되어 모집 현황에 반영돼요. 개인 정보는 표시되지 않아요.</p><div className="button-row center"><Link className="button primary" to="/plan">내 지망으로</Link><button className="button" onClick={()=>setGuide(false)}>계속 둘러보기</button></div></Modal>}</main></Shell>
}
